users:
  additional_admins:
    - '@FedinSA'
    - '@julia_tkachenko_architect'
    - '@Terra_event_bot'
    - '@Queens_go'
    - '@Oleg_Chentsov'

group:
  name_format: "{mentor_name} - TERRA, {mentor_category}, 8.0"

settings:
  disable_participant_addition: true  # Отключить добавление участников
  disable_profile_edit: true         # Запрет изменения профиля группы
  enable_anonymous_admins: false     # Анонимность для админов
  enable_topics: true                # Включить мультигруппы (темы)

topics:
  - name: "General"         # Общий чат
    pinned_message: """
🥳 Привет всем чемпионам!
Это чат наставника {mentor_name}!
Под его(её) чётким руководством в ближайшие 16 недель ты будешь идти к своей точке Б.
Помни, результат зависит в равной степени (50/50) от вашего взаимодействия с наставником! Чётко и вовремя выполняй все домашки, будь включенным и записывай инсайты каждой встречи.
🚀Первое задание - заявить о себе МИРУ (ставим хэштэг #знакомство и погнали🚀):
1. Как к тебе обращаться?
2. Ниша и твое Уникальное торговое предложение (УТП)?
3. Точка А (средний ежемесячный доход на текущий момент)
4. Точка Б (сколько планируешь заработать за ближайшие 4 месяца)
5. Что в первую очередь ждешь от Наставничества?
6. Чем можешь быть полезен для других участников группы?
😎Еще у тебя есть возможность стать помощником наставника. Помощник будет следить за своевременной отчетностью и оплатой штрафов, а взамен получит дополнительные бонусы в виде персонального разбора и большего вовлечения со стороны наставника. Если есть желание стать помощником - обязательно напиши об этом в этом чате!
Кто станет помощником, для них есть служба поддержки Терра - @terra_sochi_org
Помощнику по всем организационным вопросам можно писать на этот аккаунт.
Перед тем как начнем первое занятие, ознакомьтесь пожалуйста с правилами.

🔹Правила для участников наставничества:
1. Если наставник достиг договоренности с участником наставничества, то участник обязан выполнить ее в оговоренный срок, либо передоговориться с наставником о новых условиях.
2. Посещение занятий с наставником – договоренность (при невозможности, заблаговременно передоговориться с наставником).
3. Выполнение заданий и задач, поставленных наставником - договоренность.
4. Своевременное предоставление ежедневных отчетов - договоренность.
5. Бескорыстная помощь своим одногруппникам.
6. Пунктуальность и дисциплина.
7. Аренда помещения. Терра некоммерческий бизнес клуб и своего помещения не имеет, поэтому существует орг. взнос на аренду помещения. Сумма аренды разбивается между всеми участниками. Помещение согласуется с наставником.
8. Минута дарования. В начале каждого занятия всем ученикам необходимо выложить в своих соцсетях отзыв, в свободной форме, от том, как проходит наставничество в Терре и указать ссылку на телеграм канал Терры Сочи, скрин с отзывом отправить в группу - тема “Отзывы учеников”.
Пример подписи:
Проект наставничества реализует некоммерческий бизнес-клуб Терра Сочи
Официальный Telegram чат CHAT TERRA SOCHI @terrasochi

❌Штрафы:
1. Пропуск без предупреждения и подтверждения наставником уважительной причины – удаление.
2. Два пропуска по уважительной причине без предварительного уведомления наставника  – удаление.
3. Невыполнение заданий и задач по мм два раза подряд – удаление.
4. Нахождение в группе с целью продаж – удаление и попадание в Черный Список Терры.
5. За каждую минуту опоздания штраф – 100 руб.
6. За пропуск отчета и дз, либо несвоевременное его предоставление – штраф 500 руб.
7. Для повышения мотивации, наставник имеет право дополнить список и повысить тарифы штрафов. Повышение тарифов утверждается общим согласованием команды.
❤️Все собранные штрафы уходят в Фонд ТЕРРА Сочи, оттуда далее средства распределяются на аренду помещения и трафик первого открытого дня Терры.
ФОНД:
(чек скидывается в чат, во вкладку “Терра добро” с #терра_добро )
Как оплатить штраф:
- пройти в бот TERRA https://t.me/TERRA_event_bot?start=donation
- далее следуйте инструкциям
- чек отправляете в чат “TERRA добро” с примечанием за, что штраф
- все штрафы необходимо оплачивать до конца суток, в которые он был выставлен

📍Каждому ученику необходимо проставить СОГЛАСЕН ответом на данное сообщение!
-------------------------------------
Telegram Бизнес клуб TERRA Sochi @terrasochi
Официальный чат некоммерческого бизнес-клуба Терра
Ссылка-приглашение:  https://t.me/terrasochi
"""
  - name: "Отзывы учеников"
  - name: "Ежедневные отчёты"
    messages:
      - """
Форма ежедневного отчета согласуется с наставником.
"""
  - name: "TERRA добро"
    pinned_message:  """
❤️Все собранные штрафы уходят в Фонд TERRA Sochi, оттуда далее средства распределяются на аренду помещения и трафик первого открытого дня Терры.
ФОНД:
*(чек скидывается в чат, в тему “TERRA добро” с #терра_добро )
Как оплатить штраф:
- пройти в бот TERRA: https://t.me/TERRA_event_bot?start=donation
- далее следуйте инструкциям.
- чек отправляете в этот чат с примечанием за что штраф
- все штрафы необходимо оплачивать до конца суток, в которые он был выставлен
"""
